title: "An Update on Writing Memory Safety Bugs"
author: "Dana Jansens"
# This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
description: "How could we write better software, and write software better?"

# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "danakj@chromium.org"
#twitter_username: "twitteruser"
github_username: "danakj"
#linkedin_username: "linkedinuser"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
#theme: "minima"
remote_theme: pages-themes/midnight@v0.2.0

rss: rss

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-webmentions

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags: [ Other ]

webmentions:
  username: https://orodu.net
  cache_folder: .cache
  legacy_domains:
    - http://danakj.github.io
  templates:
    count: _includes/webmentions/count.html
    likes: _includes/webmentions/likes.html
    links: _includes/webmentions/links.html
    posts: _includes/webmentions/posts.html
    replies: _includes/webmentions/replies.html
    reposts: _includes/webmentions/reposts.html
    webmentions: _includes/webmentions/webmentions.html
  max_attempts: 5
  bad_uri_policy:
    unsupported:
      policy: ban
    error:
      policy: ignore
    failure:
      policy: retry
      retry_delay: [ 1, 12, 48, 120 ]
      max_retries: 5
    whitelist:
      - "^https://brid.gy/publish/"
    blacklist:
      - "^https://foo.bar/"
  syndication:
    mastodon: 
      endpoint: https://brid.gy/publish/mastodon
      response_mapping:
        syndication: $.url
    github: 
      endpoint: https://brid.gy/publish/github
